### ISSUE TITLE
iOS single tap Full screen mode

### ISSUE THREAD

**Issue by antondys** [kiwix/kiwix-apple#457]
Hello and many thanks for the magnificent app! What I miss (and many others users too, no doubt) is the full screen mode activated e.g. with a single tap on the screen. It will make reading much more immersive if one could hide the top and bottom bars when they are not in use. Do not waste screen space, there is not plenty of it even on big phones. And this is a standard feature on most ebook reader apps, should be pretty simple to implement..

**Comment by kelson42** [comment]
@BPerlakiH Considering we focus current meilestone on fixing videos bugs, I though it would make sense tomget that one as well. Do you understand the feature request? Is this doable?

**Comment by kelson42** [comment]
Here we should have a precise proposal about how it should work. I'm not an iOS user and I'm not familiar with the "on tap" but beside this point the fullscreen function should:
* Work fine on both macOS and iOS/iPadOS
* Usually the "bars" should disappear after a few seconds if not used in fullscreen mode
* Should perfectly work with the video fullscreen mode

**Comment by TheRealAnt** [comment]
iOS:
Apple Books app example: https://github.com/kiwix/kiwix-apple/assets/22860503/c164444b-c550-4877-9677-3af62bf4f66e

1. When you single tap anywhere on the screen, the top navigation bar and bottom tab bar are hidden & enter the "immersive/full screen reading" mode.
2. While in the "immersive reading mode", the user can still slide gesture on the screen to continue reading.
3. To exit the "immersive reading mode", the user can single tap anywhere on the screen again to see the top and bottom bars again.

iPad:
I don't own one, but I assume it works the same as iOS.

MacOS:
No Books app for Mac, used Yomu app example: https://github.com/kiwix/kiwix-apple/assets/22860503/7058327a-fb98-42e4-b724-5c77509b347d

1. Same single tap to enter/exit an "immersive reading" mode.
2. Had to use arrow keys to navigate while in this mode, dragging mouse on screen didn't seem to work.

@kelson42 We'll most probably only be able to see if this single tap gesture & video fullscreen mode behaviour possibly clash in some way during implementation.

**Comment by BPerlakiH** [comment]
I have the following thoughts on this:
- it is an iPhone only issue, on iPads, we have the menu items on the top, similarly on macOS (plus on macOS there’s even a system button to make the window full screen)
the suggested “one click” solution is working on eBook readers (and similar non-interactive content), but our content in many cases is interactive, such as links, audio and video as well. In our case the single tap is not the ideal solution (eg: if you tap on a link the full screen switch should not trigger, if you want to tap a link, but you miss it, full-screen will trigger, which might be frustrating).
In order to gain more “reading space” I am suggesting to implement the “minimise tab bar on scroll” solution, similarly to safari (for iPhones)

**Comment by TheRealAnt** [comment]
@BPerlakiH hmm yes I see what you're saying about the single tap on links & missing the tap.
I agree with your “minimise tab bar on scroll” solution, it's a smooth experience.
