### ISSUE TITLE
DWDS First time error message

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-apple#633]
When downloading testflight macOS builds, I get the following error message

<img width="1012" alt="Screenshot 2024-01-22 at 17 44 29" src="https://github.com/kiwix/apple/assets/57929/61effee1-77d5-4d7c-86e4-2dd7ef405ff5">

It doesn't seem to appear when I manually cleanup the App's internal cache/containers files.

Can you please check whether this is something that can happen outside of TestFlight? I know @Popolechien is also affected.

**Comment by BPerlakiH** [comment]
This is a consequence of #601 - handling the bookmarks (or formerly saved state of the application).
Since we save the bookmarks and formerly opened articles based on the assumption that the ZIM file is the same.
Upon updating the app to another ZIM file, our assumption is no longer true.

For the moment it is not affecting end users, as they will only have 1 version of the app, but it would be nice to fix before the next release (with a new ZIM file) goes out to the store.

**Comment by BPerlakiH** [comment]
@rgaudin can you re-test this please with DWDS, as far as I remember this should be solved now.

**Comment by rgaudin** [comment]
Haven't been able to reproduce in a while
