### ISSUE TITLE
iOS Library downloads hang consistently

### ISSUE THREAD

**Issue by dustinfreeman** [kiwix/kiwix-apple#733]
I've had downloads hang without progress or error message hang consistently over the past week. Progress of the download proceeds normally and then stops without movement for hours.

Expected behaviour: the download completes, or gives an explicit error for why it is paused without progress.

![IMG_3191](https://github.com/kiwix/kiwix-apple/assets/940836/d2c6bb98-5a73-4bac-93f4-f63f9be2ab67)

![IMG_3192](https://github.com/kiwix/kiwix-apple/assets/940836/fda3b59d-ae63-4055-b43e-f0abf975464c)

Device:
- iPhone SE, 3rd generation 
- iOS 17.4.1
- more than enough storage space

I'm on the current version of the Kiwix App, as of the App Store.
I am on internet at my home in NYC, and otherwise my connection works fine. I am able to download Kiwix libraries to desktop. I have tried restarting the app, my phone, restarting the download, etc.

Any debugging methods or tips welcome.

**Comment by kelson42** [comment]
@BPerlakiH Is that a behaviour you can reproduce? I don‘t have enough mass storage to download such a large file myself.

**Comment by BPerlakiH** [comment]
As of my observation once it crosses the 1GB limit, the frequency of the progress updates are slower (since it's a larger format).
There will be some improvements in regarding the download progress in our upcoming 3.3 kiwix release.
I did managed to get higher with the download than the 2.2GB attached, so the file itself seem to be fine.
![Screenshot 2024-04-23 at 23 49 46 Medium](https://github.com/kiwix/kiwix-apple/assets/6784320/89448569-8d19-41b8-a4c1-c7cac948a6be)

One tip: If you already have the ZIM file downloaded on your desktop, there's no need to download it again to your phone, you can copy it over to your iPhone (my guess is that the quickest will be by using a USB cable).
Once you copied it to your phone, you can open the ZIM file by tapping on it (within the "Files" app), that will automatically open the associated Kiwix app and "import" that ZIM file into the Kiwix application, and from that moment you can use it the same way.

**Comment by kelson42** [comment]
@dustinfreeman We have finally released version 3.3.0 which brings a lot of improvements. Do you still suffer of this bug with latest Kiwix version?

**Comment by dustinfreeman** [comment]
> @dustinfreeman We have finally released version 3.3.0 which brings a lot of improvements. Do you still suffer of this bug with latest Kiwix version?

On Kiwix 3.3.0, same download as before just succeeded! However, this success may also be due to another reason: I have since upgraded my device to an iPhone 15 Pro with 256 GB, currently on iOS 17.5
