### ISSUE TITLE
Test zimit2 support

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-apple#781]
With the upcoming release of zimit2, we want to ensure we have decent zimit2 ZIM support in Apple Reader.

@benoit74 can  you share a ZIM of the test-website so that we have a good example of special cases that should be handled? Or is that not appropriate?
We are very interested in a ZIM with Youtube video player inside.

**Comment by benoit74** [comment]
I'm opening one issue per ZIM in zim-requests so that it is easier to report / track progress for testers.

Currently we have 3 ZIMs which have been deemed interesting to test:
- https://github.com/openzim/zim-requests/issues/1011
- https://github.com/openzim/zim-requests/issues/1014
- https://github.com/openzim/zim-requests/issues/1015

There is little to test for now because all zimit2 ZIMs are mostly blocked on kiwix-apple by https://github.com/kiwix/kiwix-apple/issues/779 where I AFH.

Once this is solved, please report issues you find in these original tickets so that I can triage them. We should avoid to rush into fixing issues reader-side, since there is a significant probability it could be a scraper issue. Triage is mandatory.

I will soon add few more ZIMs.  

Should I assign @BPerlakiH to these tickets as well so that you are informed when new ZIM arrives?

**Comment by kelson42** [comment]
@rgaudin The test ZIM files has already been test at https://github.com/kiwix/kiwix-apple/issues/698

**Comment by benoit74** [comment]
https://github.com/openzim/zim-requests/issues/1023

**Comment by kelson42** [comment]
@BPerlakiH Any other known bug with these three test files (beside #799)?

**Comment by kelson42** [comment]
@benoit74 What should we do with this issue? Do we want to usenit tomtest a large number of ZIM files during a long time?

**Comment by kelson42** [comment]
> Should I assign @BPerlakiH to these tickets as well so that you are informed when new ZIM arrives?

Yes please

**Comment by benoit74** [comment]
> What should we do with this issue? Do we want to usenit tomtest a large number of ZIM files during a long time?

From my PoV, we should close this issue. First because I do not intend to continue to produce test Zimit2 ZIMs on a regular basis, might happen I ask to test a new ZIM next time we make significant changes, but this is not going to be a regular thing. Second because it is now clear that I will tag BPerlakiH in these issues just like I tag Jaifroid to test "JS" readers. And third because last tests and changes have now brought apple readers to a stable support of Zimit2 from my perspective.
