### ISSUE TITLE
Download error feedback

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-apple#900]
I have two distinct bugs in this short screencast:

- My library is outdated (2 months old), despite having checked to update automatically.
- When trying to download a ZIM that's missing (proxyman tells me it results in a `404` for https://download.kiwix.org/zim/wikipedia/wikipedia_en_golf_maxi_2024-04.zim), I have zero feedback that there has been an error.

https://github.com/user-attachments/assets/d7a11a44-0689-4862-9a39-5bea39ef2839

**Comment by BPerlakiH** [comment]
Ok, I think we need to split this issue into 2 parts:
1) we need to find out why you have 2 months old library, when you have auto-refresh on. It might be related some older debug version of the app, that you might "stuck" with, without clearing the app install folder. It might be only local to you, but might be a "real" user update issue.
2) For now let's focus on the download issue, since you are stuck in this phase, that's the ideal "test environment" for us. I will have a look at how the download errors are handled, and if we could possibly apply a user facing alert at least.

**Comment by BPerlakiH** [comment]
The error handling part is fixed here: https://github.com/kiwix/kiwix-apple/pull/912

**Comment by BPerlakiH** [comment]
I moved the outdate library issue here: https://github.com/kiwix/kiwix-apple/issues/922
and renamed this one to be related to the download error only.
