### ISSUE TITLE
Add trader status in App Store Connect

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-apple#942]
From Apple:

> Hello,
> As a reminder, you need to enter your trader status in App Store Connect for apps on the App Store in the European Union (EU) in order to comply with the Digital Services Act.
> Learn what a trader is and how to enter your status.
> Please note these new dates and requirements:
> October 16, 2024: Trader status will be required to submit app updates. If you’re a trader, you’ll need to provide your trader information before you can submit your app for review.
> February 17, 2025: Apps without trader status will be removed from the App Store in the EU until trader status is provided and verified.
> If you have any questions, contact us.
> The Apple Developer Relations Team

**Comment by kelson42** [comment]
@BPerlakiH Can you please to that one quickly so we can close this issue?

**Comment by BPerlakiH** [comment]
@kelson42 I have looked into this, it requires an Admin or Account Holder account (which I do not have).
The details of what and how to enter is here:
https://developer.apple.com/help/app-store-connect/manage-compliance-information/manage-european-union-digital-services-act-trader-requirements/

**Comment by kelson42** [comment]
@Popolechien Do you have the permissions to do that?

**Comment by Popolechien** [comment]
As far as I can tell we have identified as non-trader already and we should be good. I'm not getting any of these alerts so @BPerlakiH could it be because you are registered as developer for other apps?
![Screenshot 2024-09-04 at 11 06 36](https://github.com/user-attachments/assets/bf7db0ff-1303-409c-9961-1b524a888b75)
![Screenshot 2024-09-04 at 11 07 52](https://github.com/user-attachments/assets/2f5401fa-f936-4456-9442-6a994c529055)

**Comment by Popolechien** [comment]
Ok I've punched again the DSA button just to be on the safe side and got the below confirmation, I think we should be good now
![Screenshot 2024-09-04 at 11 12 34](https://github.com/user-attachments/assets/96b7b9b2-d285-4ff7-9e39-78cd1af430dc)
