### ISSUE TITLE
Stop having allowing multiple windows

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-apple#969]
We should jühave only one window to:
* easily ensure coherency
* ensure it does not work very differently from other Kiwix

**Comment by benoit74** [comment]
I'm significantly not aligned with this change, at least as it is described / justified for now. 

As a Mac user, I generally dislike applications which do not support multiple windows (there are few edge cases of course where I know I need only one window in all cases), and I think that I'm not alone, (as rgaudin said) this is quite expected by most Mac users to be able to have multiple windows of the same applications for various use cases.

That being said, I have no idea about the exact cost associated with multiple windows, and it might make sense if we do not have the resources required to maintain a multiple windows application. It would be sad, but that might be our reality, and I prefer a limited but not buggy application. This needs to be a bit more grounded than "it would be simpler".

The argument "ensure it does not work very differently from other Kiwix" makes non sense from my PoV, we do not have any kind of standard behavior across Kiwix readers, and it is even known to be an anti-pattern because each OS/community has its "way of working" and it is recommended to align with them rather than provide a one-size-fit-all solution.

**Comment by kelson42** [comment]
@benoit74 Thx for your feedback. @rgaudin has a similar opinion I believe. I will let the issue maturing... or die.

**Comment by BPerlakiH** [comment]
I am somewhat aligned with @rgaudin and @benoit74 on this.
Currently the only way to open a link in a new tab is a standard feature across all versions of Apple Kiwix. Detaching a tab from the current window is a standard feature of macOS.
Therefore we have multiple tabs which is equal multiple windows.
I also think that removing tabs or forcing to have a single window would be too much limiting on our users.

**Comment by kelson42** [comment]
Considering that everybody agrees on this feature/behaviour (except me), lets keep it like this for the moment.
